version: "3.8"

services:
  integrator-mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank_account
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    networks:
      - app-network
    depends_on:
      - integrator-mysql
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "mysql://admin:admin@mysql:3306/bank_account"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app
    command: npm run dev

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
